### ISSUE TITLE
Solicitud para aceptar la petición enviada para el uso de Travis.

### ISSUE THREAD

**Issue by jorgegaguilar** [EGC-G2-Trabajo-1718/integracion#1]
Prioridad: alto
Estado: pendiente
Descripción: Desde cabina de votación estamos interesados en el uso de Travis para la inclusión de integración continua. 
Se ha enviado una petición al correo electrónico que esté asignado para esta organización.
Espero su respuesta, gracias.

**Comment by robgc** [comment]
La integración continua se realizará mediante Travis CI en el servidor de producción. Lamentablemente no es posible cambiar esto puesto que ya hemos realizado tareas relativas a esto y produciría retrasos.

**Comment by NachoAlesLopez** [comment]
Buenos días
¿Cómo se podrá entonces preparar la integración continua que solicitan en el siguiente milestone? Parece requerir que cada repositorio realice la integración continua de su trabajo, de forma que pueda suministrarse cuanto antes un producto funcionando en pre producción y producción.

**Comment by robgc** [comment]
Me he confundido antes. La integración se realizará mediante Jenkins en el servidor de despliegue. Jenkins realizará las tareas de construcción e integración correspondientes y creará un nuevo contenedor con los resultados. Cada vez que un nuevo commit se suba a las ramas de dev y master se realizará el proceso de construcción, sin embargo, solo se desplegarán los resultados de master.

**Comment by robgc** [comment]
Todos los grupos tendrán acceso de lectura a los resultados de las compilaciones. Publicaremos en la wiki más detalles cuando todo esté listo.
