### ISSUE TITLE
Error despliegue Travis

### ISSUE THREAD

**Issue by PabloTinoco** [EGC-G2-Trabajo-1718/integracion#2]
Prioridad: urgente

A la hora de realizar el despliegue en travis, estamos obteniendo el siguiente error:

chmod 600 deploy && mv deploy ~/.ssh/id_rsa
chmod: cannot access ‘deploy’: No such file or directory

![image](https://user-images.githubusercontent.com/22832288/34649533-68031abe-f3b1-11e7-835b-dc4cee92fabc.png)

Ya se ha descomentado la linea que nos correspondia.

**Comment by robgc** [comment]
Ese fallo se debe a que en vuestro repositorio no hemos añadido el fichero **deploy**. En la plantilla hay un comentario indicando que debemos añadir dicho fichero a vuestro repositorio **https://github.com/EGC-G2-Trabajo-1718/integracion/blob/master/travis/template.yml#L7.** En breve realizaré un commit para añadir dicho fichero.
