### ISSUE TITLE
Nuestro repositorio no contiene deploy.enc

### ISSUE THREAD

**Issue by migueltern** [EGC-G2-Trabajo-1718/integracion#3]
Prioridad:  urgente.
Descripción: No tenemos el fichero deploy.enc en nuestro repositorio, según dice vuestra wiki vuestro equipo tiene que proveernos de ella.

Somos el grupo censos.

**Comment by robgc** [comment]
Para poder añadir el fichero deploy.enc la herramienta Travis CLI requiere la existencia del fichero .travis.yml en vuestro repositorio. No he encontrado dicho fichero en ninguna rama de vuestro repositorio, cuando lo hayáis subido añadiré los elementos necesarios a la rama correspondiente.

**Comment by migueltern** [comment]
Prioridad: urgente.
Descripción: Acabamos de subir el archivo .travis.yml para que podáis añadir los elementos necesarios. [1faed1f](https://github.com/EGC-G2-Trabajo-1718/egc-censos/commit/1faed1f)

**Comment by robgc** [comment]
El siguiente commit cierra este issue: EGC-G2-Trabajo-1718/egc-censos@1faed1f
