### ISSUE TITLE
Dificultades al realizar el despliegue de cabina de votaciones

### ISSUE THREAD

**Issue by NachoAlesLopez** [EGC-G2-Trabajo-1718/integracion#5]
Como puede verse en el siguiente proceso de Travis, https://travis-ci.org/EGC-G2-Trabajo-1718/cabina-de-votacion/jobs/328413011. El proceso de despliegue se queda atascado esperando input del usuario. Se presenta la traza del proceso de despliegue:
`
Deploying application
The authenticity of host 'egc.duckdns.org (150.214.142.26)' can't be established.
'ECDSA key fingerprint is 2e:f1:13:f9:3a:3d:86:8a:98:4c:07:fc:21:00:8d:db.
Are you sure you want to continue connecting (yes/no)?
`

**Comment by robgc** [comment]
Disculpa las molestias, detectamos dicho fallo en uno de los subsistemas pero no habíamos actualizado la plantilla en nuestro repositorio. En breve actualizaremos la plantilla y notificaremos a todos los coordinadores.

**Comment by robgc** [comment]
Ya hemos solucionado la incidencia en el siguiente commit https://github.com/EGC-G2-Trabajo-1718/integracion/commit/d8db05cf6a00b4bce644feb42cb137e1eb9cd360 . Tenéis que actualizar vuestro fichero .travis.yml con los cambios realizados.
