### ISSUE TITLE
Error producido en una de los despliegues de cabina de votaciones

### ISSUE THREAD

**Issue by NachoAlesLopez** [EGC-G2-Trabajo-1718/integracion#6]
En el siguiente proceso de Travis: https://travis-ci.org/EGC-G2-Trabajo-1718/cabina-de-votacion/jobs/328418572, puede verse como el despliegue falla, pero en otro de los procesos, que usa como versión de node la 9, no se produce el fallo.

Me gustaría conocer, por tanto, si mi módulo queda desplegado, ya que este error parece dar a entender que se ha intentado desplegar 2 veces.

**Comment by robgc** [comment]
En vuestro fichero `.travis.yml` especificáis dos versiones de Node.js a utilizar. Esto hace que se realicen dos construcciones del código en Travis de forma paralela. El fallo se produce porque el script de despliegue en producción solo está pensado para desplegar una única build.

https://github.com/EGC-G2-Trabajo-1718/cabina-de-votacion/blob/396373a963b73c8a3a0d066c597428182d08c30d/.travis.yml#L9

Tenéis que especificar en qué builld se despliega indicando la versón en la sección **"on:"**. Aquí tenéis más información:

https://docs.travis-ci.com/user/deployment/#Examples-of-Conditional-Deployment
