### ISSUE TITLE
Desplegar subsistema

### ISSUE THREAD

**Issue by PabloTinoco** [EGC-G2-Trabajo-1718/integracion#7]
Una vez tenemos en marcha la máquina virtual, que pasos debemos seguir para desplegar nuestro subsistema.

_SO: Window 10
Sistema: Administración de votaciones_

**Comment by robgc** [comment]
Hace unas semanas anunciamos que habíamos añadido información al respecto en la wiki de la asignatura. En el siguiente enlace debería haber suficiente información al respecto:

https://1984.lsi.us.es/wiki-egc/index.php/Equipo_de_integraci%C3%B3n_general_-_17_18_-_G2#Scripts_de_automatizaci.C3.B3n

**Comment by martos93** [comment]
Prioridad: Alta

Al ejecutar la máquina virtual y seguir los pasos, se recibe un error de conectividad. Se adjunta captura del error.

![captura](https://user-images.githubusercontent.com/13450875/34908014-19c0c612-f889-11e7-9793-67d5f2f87b8d.PNG)

Se ha probado a hacer ping a google y otras web recibiendo  error de conexión:

![captura2](https://user-images.githubusercontent.com/13450875/34908044-9962d0cc-f889-11e7-86b1-6f6ef2094511.PNG)

**Comment by martos93** [comment]
Se ha conseguido realizar la ejecución de los scripts especificados en la wiki, pero no podemos acceder por url desde el navegador a la máquina virtual (El ordenador local no reconoce ninguna ip de la maquina virtual).

**Comment by robgc** [comment]
La incidencia original se cerró, si hay una incidencia nueva se debe crear una nueva.
