### ISSUE TITLE
Problemas con máquina virtual

### ISSUE THREAD

**Issue by martos93** [EGC-G2-Trabajo-1718/integracion#8]
Prioridad: alta

Se ha conseguido realizar la ejecución de los scripts especificados en la wiki, pero no podemos acceder por url desde el navegador a la máquina virtual (El ordenador local no reconoce ninguna ip de la maquina virtual).

**Comment by robgc** [comment]
En la wiki está indicado como se accede a un subsistema desde fuera de la máquina virtual. Leed bien la documentación, por favor. https://1984.lsi.us.es/wiki-egc/index.php/Equipo_de_integraci%C3%B3n_general_-_17_18_-_G2#M.C3.A1quina_virtual_de_desarrollo
